controllers/EventController.php
<?php

namespace app\controllers;

use Yii;
use app\api\modules\v1\models\Events;
use app\api\modules\v1\models\SearchEvents;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\api\modules\v1\models\EventsAtendees;
use app\api\modules\v1\models\EventsSponsors;
use yii\filters\AccessControl;
use yii\web\Session;
use yii\helpers\Json;

/**
 * EventController implements the CRUD actions for Events model.
 */
class EventController extends Controller {

    public function init() {
        $userid = Yii::$app->session['user_id'];
        if ($userid == '') {
            $this->redirect(Yii::$app->params['server'] . Yii::$app->params['servername'] . '/site/login');
        }
        parent::init();
    }

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['create', 'update', 'view'],
//                'rules' => [
//                    // allow authenticated users
//                    [
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                // everything else is denied
//                ],
//            ],
        ];
    }

    /**
     * Lists all Events models.
     * @return mixed
     */
    public function actionIndex() {

        $searchModel = new SearchEvents();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['active' => 1]);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Events model.
     * @param integer $id
     * @param integer $venue_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id, $venue_id) {
        return $this->render('view', [
                    'model' => $this->findModel($id, $venue_id),
        ]);
    }
    
    public function actionEventattendees() {
        
        if (!empty($_POST)){
            
        $eventid = $_POST['event_id'];
        
        return $this->redirect(array('eventattendees', 
                    'eventid' => $eventid)
        );
        }
        return $this->render('eventattendees');
    
    }

    public function actionEventsponsors() {
        
        if (!empty($_POST)){
            
        $eventid = $_POST['event_id'];
        
        return $this->redirect(array('eventsponors', 
                    'eventid' => $eventid)
        );
        }
        return $this->render('eventattendees');
    
    }
    
    public function actionInactiveuser(){
        
        $id= $_GET['id'];
        $eventid = $_GET['eventid'];
        Yii::$app->db->createCommand("DELETE FROM eventattendees WHERE events_id = '$eventid' and user_id = '$id' ")->execute();
        //$this->findModel($id)->delete();

        return $this->redirect(['eventattendees']);
        
    }

    /**
     * Creates a new Events model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Events();
        //get the instance of the uploaded file

        if ($model->load(Yii::$app->request->post())) {
            $servername = Yii::$app->params['servername'];
            //to-do check if the file exist
            //if it is overwrite>??

            if ($model->file !== '') {
                $model->file = UploadedFile::getInstance($model, 'file');
                $model->file->saveAs('uploads/events/' . $model->file->baseName . '.' . $model->file->extension);
                $model->image_cover = "" . $servername . '/uploads/events/' . $model->file->baseName . '.' . $model->file->extension . "";
            }
            if ($model->save(false)) {
                return $this->redirect(['view', 'id' => $model->id, 'venue_id' => $model->venue_id]);
            }
        }
        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Events model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param integer $venue_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id, $venue_id) {
        $model = $this->findModel($id, $venue_id);

        if ($model->load(Yii::$app->request->post())) {
            $servername = Yii::$app->params['servername'];
            //to-do check if the file exist
            //if it is overwrite>??
             $templogo = UploadedFile::getInstance($model, 'file');
//            var_dump($templogo);
//            exit;
             if ($templogo !== null) {
                $model->file = UploadedFile::getInstance($model, 'file');
                $model->file->saveAs('uploads/events/' . $model->file->baseName . '.' . $model->file->extension);
                $model->image_cover = "" . $servername . '/uploads/events/' . $model->file->baseName . '.' . $model->file->extension . "";
            }
            if ($model->save(false)) {
                return $this->redirect(['view', 'id' => $model->id, 'venue_id' => $model->venue_id]);
            }
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Events model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param integer $venue_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id, $venue_id) {

        Yii::$app->db->createCommand()->update('events', ['active' => 0], ['id' => $id, 'venue_id' => $venue_id,])->execute();
        //$this->findModel($id, $venue_id)->delete();

        return $this->redirect(['index']);
    }


    public function actionAssign() {

         if (!empty($_POST)){
            
        $eventid = $_POST['event_id'];
        
        return $this->redirect(array('assign', 
                    'eventid' => $eventid)
        );
        }
        return $this->render('assign');

        //return $this->render('assign');
    }

    /**
     * Finds the Events model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param integer $venue_id
     * @retur
     n Events the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $venue_id) {
        if (($model = Events::findOne(['id' => $id, 'venue_id' => $venue_id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


//     public function actionAssignevent() {
//         $eventid = $_POST['eventid'];
//         $userid = $_POST['users'];
// //        var_dump($userid);
// //        exit;
//         //assume all validatuion have been completed
//         //$finalUserArr = [];
//         foreach ($userid as $anId) {
//             // $temp = [$eventid, $anId];
//             // array_push($finalUserArr, $temp);

//             Yii::$app->db->createCommand()->batchInsert('eventattendees', ['events_id'=>$eventid], ['user_id'=>$anId,])->execute();
//         }
//         return $this->redirect(['assign']);
//     }

    /*
     * Assign users to an event
     * add users to events attentdees
     */

    

    public function actionAssignevent() {
        $eventid = $_POST['eventid'];
        $userid = $_POST['users'];
//        var_dump($userid);
//        exit;
        //assume all validatuion have been completed
        $finalUserArr = [];
        foreach ($userid as $anId) {
            $temp = [$eventid, $anId];
            array_push($finalUserArr, $temp);
        }
        $sucess = EventsAtendees::assignUsers($finalUserArr);
        echo $sucess;
    }

    /*
     * remove user from an event
     */

    public function actionDeactivateuser() {
        $eventid = $_POST['eventid'];
        $userid = $_POST['users'];

        foreach ($userid as $anId) {
            //$temp = [$userid, $anId];
            $result = EventsAtendees::deactivateAttendees($eventid, $anId);
        }
        //  $sucess = EventsSponsors::assignSponsors($finalSponsorArr);
        echo $result;
    }

    /*
     * Assign speakers to an event
     */

    public function actionAssignsponsor() {
        return $this->render('assignSponsors');
    }

    public function actionTransfersponsor() {
        $eventid = $_POST['eventid'];
        $sponsorid = $_POST['sponsors'];

        //assume all validatuion have been completed
        $finalSponsorArr = [];
        foreach ($sponsorid as $anId) {
            $temp = [$eventid, $anId];
            array_push($finalSponsorArr, $temp);
        }
        $sucess = EventsSponsors::assignSponsors($finalSponsorArr);
        echo $sucess;
    }

    public function actionGetnotusers() {
        $eventid = $_POST['eventid'];//this is the event id passed from the ajax post
        $eventattendees = EventsAtendees::getusersnot($eventid);//get the list of users not have been assigned

        $data = $this->renderPartial('_attendpartial', array('eventattendees' => $eventattendees), false, true);//this is renderpartial the view
        return Json::encode($data);//remember to json encode the data.....__attendpartial.php
    }

views/event/_attendpartial.php
<?php

use yii\grid\GridView;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<div class="table">
    <?=
    GridView::widget([
        'dataProvider' => $eventattendees,
        'filterModel' => $searchModel,
        'id' => 'usergrid',
        'columns' => [

            'first_name',
            'last_name',
            ['class' => 'yii\grid\CheckboxColumn'],
        ],
    ]);
    ?>
    <div class="box-footer">
        <div class="row pull-right">
            <input type="submit" class="btn btn-success" id="btn-assignUser" value="Assign" />
            <!--input type="submit" class="btn btn-danger" id="btn-removeuser" value="Remove" /-->
        </div>

    </div>
</div>

views/event/_attendsponsors.php
<?php

use yii\grid\GridView;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>


<div class="table">
    <?=
    GridView::widget([
        'dataProvider' => $eventsponors,
        'filterModel' => $searchModel,
        'id' => 'sponsorgrid',
        'columns' => [

            'companyname',
            
            ['class' => 'yii\grid\CheckboxColumn'],
        ],
    ]);
    ?>
    <div class="box-footer">
        <div class="row pull-right">
            <input type="submit" class="btn btn-success" id="btn-assignSponsors" value="Assign" />

            <!--input type="submit" class="btn btn-danger" id="btn-removeuser" value="Remove" /-->
            
        </div>

    </div>
</div>

views/event/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use app\api\modules\v1\models\Venue;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Create Events</h3>
    </div>

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="box-body">
        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

        <?php if($model->isNewRecord){
            echo $form->field($model, 'file')->fileInput();
        }else{
             echo Html::img(Yii::$app->params['server'] . $model->image_cover, ['width' => '150px']);
             echo $form->field($model, 'file')->fileInput();
        }
        ?>

        <?=
        $form->field($model, 'start_date')->widget(
                DatePicker::className(), [
            // inline too, not bad
            'inline' => false,
            // modify template for custom rendering
            //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
            'clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-m-dd'
            ]
        ]);
        ?>

        <?=
        $form->field($model, 'end_date')->widget(
                DatePicker::className(), [
            // inline too, not bad
            'inline' => false,
            // modify template for custom rendering
            //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
            'clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-m-dd'
            ]
        ]);
        ?>

<?=
$form->field($model, 'venue_id')->dropDownList(
        ArrayHelper::map(Venue::find()->all(), 'id', 'name'), ['prompt' => 'Select Venue']
)
?>

    </div>
    <div class="box-footer">
<?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

<?php ActiveForm::end(); ?>

</div>

views/event/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\SearchEvents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'start_date') ?>

    <?= $form->field($model, 'end_date') ?>

    <?php // echo $form->field($model, 'active') ?>

    <?php // echo $form->field($model, 'lastmodified') ?>

    <?php // echo $form->field($model, 'image_cover') ?>

    <?php // echo $form->field($model, 'venue_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event/assign.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use app\api\modules\v1\models\Venue;
use yii\helpers\ArrayHelper;
use richardfan\sortable\SortableGridView;
use yii\data\ActiveDataProvider;
use app\api\modules\v1\models\Events;
use app\api\modules\v1\models\EventsAtendees;
use app\api\modules\v1\models\User;
use app\api\modules\v1\models\SearchUser;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */
/* @var $form yii\widgets\ActiveForm */


$this->title = 'Assign Users to Event';
$this->params['breadcrumbs'][] = $this->title;



<<<<<<< HEAD
$events = new app\api\modules\v1\models\Events();

 $searchModel = new SearchUser();
=======
$eventAtendees2 = new app\api\modules\v1\models\EventsAtendees();
>>>>>>> c192da466b27642619e1207f0604215ebe4f79e8


if (!empty($_GET)){
    $eventid = $_GET['eventid'];
    $model = Events::findOne($eventid);
}


?>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>
<<<<<<< HEAD
    <?php $form = ActiveForm::begin(); ?>
=======
    <?php $form = ActiveForm::begin(['action' => 'EventController/assign' , 'id'=>'EventController', 'method' => 'post',]); ?>
>>>>>>> c192da466b27642619e1207f0604215ebe4f79e8

    <div class="box-body">

        <?=
<<<<<<< HEAD
        $form->field($events, 'event_id')->dropDownList(
=======
        $form->field($eventAtendees2, 'event')->dropDownList(
>>>>>>> c192da466b27642619e1207f0604215ebe4f79e8
                ArrayHelper::map(Events::find()->all(), 'id', 'name'), ['prompt' => 'Select the Events']
        )
        ?>
        <!-- <br>
        <h4>List of Users that have not been assigned to this Event</h4>
        <br> -->


    </div>
<<<<<<< HEAD
    <?php ActiveForm::end(); ?>
    <?php
        if (!empty($_GET)){
         
        $sbsquery = Eventsatendees::find()->select('user_id')->where(['events_id' => $eventid]);
        $modeluser = User::find()
                ->where(['NOT IN', 'id', $sbsquery]);

        //$passevent = 'id';
        
        // $dataProvider2 = new ActiveDataProvider([
        //     'query' => $modeluser,
        // ]);


        $dataProvider2 = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider2->query->andWhere(['NOT IN', 'id', $sbsquery]);


        ?>


        <div style="font-size: 20px; margin-left: 10px; margin-bottom:30px; text-transform: uppercase">
        <label>Assign Attendees Not Yet Assigned to Event : <?= Html::getAttributeValue($model, 'name') ?></label>
    </div>

    
    </div>
    <?= GridView::widget([
            'dataProvider' => $dataProvider2,
            'filterModel' => $searchModel,
=======
    




    <?php
        if (!empty($_GET)){
         
        $sbsquery = Eventsatendees::find()->select('user_id')->where(['events_id' => $eventid]);
        $model = User::find()
                ->where(['NOT IN', 'id', $sbsquery]);
        
        $dataProvider2 = new ActiveDataProvider([
            'query' => $model,
        ]);?>
   

    </div>
    <?= GridView::widget([
            'dataProvider' => $dataProvider2,
>>>>>>> c192da466b27642619e1207f0604215ebe4f79e8
            'id' => 'userlistgrid',

            // SortableGridView Configurations
            //'sortUrl' => \yii\helpers\Url::to(['sortItem']),
            //'sortingPromptText' => 'Loading...',
            //'failText' => 'Fail to sort',

            'columns' => [
                // Data Columns
                'first_name',
                'last_name',
                //'active',
                //'lastmodified',
                // 'events_id',
                // 'venue_id',
                ['class' => 'yii\grid\CheckboxColumn'],
            ],
        ]);



?>

<<<<<<< HEAD
=======
<?php ActiveForm::end(); ?>

 <div class="box-footer">
        <div class="row pull-right">
            <input type="submit" class="btn btn-success" id="btn-assignUser" value="Assign" />
            <!--input type="submit" class="btn btn-danger" id="btn-removeuser" value="Remove" /-->
        </div>

    </div>
>>>>>>> c192da466b27642619e1207f0604215ebe4f79e8


    
    <?php    
        } ?>
    <!-- <div id="ajaxloaded">
    </div> -->


</div>

<div class="box-footer">
        <div class="row pull-right">
            <input type="submit" class="btn btn-success" id="btn-assignUser" value="Assign" />
            <!--input type="submit" class="btn btn-danger" id="btn-removeuser" value="Remove" /-->
        </div>

    </div>

views/event/assignSponsors.php
<?php

//use yii\helpers\Html;
use yii\widgets\ActiveForm;
//use dosamigos\datepicker\DatePicker;
//use app\api\modules\v1\models\Venue;
use yii\helpers\ArrayHelper;
use app\api\modules\v1\models\Events;
use app\api\modules\v1\models\EventsSponsors;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */
/* @var $form yii\widgets\ActiveForm */
$eventsponsors = new app\api\modules\v1\models\EventsSponsors();

$this->title = 'Assign Sponsors to Event';
?>

<div class="box box-primary">
   <div class="box-header with-border">
       <h3 class="box-title">Assign Sponsors to an Event</h3>
   </div>
   <?php $form = ActiveForm::begin(['action' => ['event/assignevent'], 'method' => 'post',]); ?>

   <div class="box-body">

       <?=
       $form->field($eventsponsors, 'events_id')->dropDownList(
               ArrayHelper::map(Events::find()->all(), 'id', 'name'), ['prompt' => 'Select Events']
       )
       ?>

       <br>
       <h4>List of Sponsors</h4>
       <br>
      
   </div>


<?php ActiveForm::end(); ?>

   <div id="ajaxdataloaded">

    </div>
    
</div>

views/event/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */

$this->title = '';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event/eventattendees.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\api\modules\v1\models\EventsAtendees;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\api\modules\v1\models\Events;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Event Attendees';
$this->params['breadcrumbs'][] = $this->title;

$event = new app\api\modules\v1\models\Events();

if (!empty($_GET)){
    $eventid = $_GET['eventid'];
    $model = Events::findOne($eventid);
}

?>
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        
    </div>
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body">

       <?=
        $form->field($event, 'event')->dropDownList(
                ArrayHelper::map(Events::find()->all(), 'id', 'name'), ['prompt' => 'Select Events']
        )
        ?>
        
     
    </div>
    <?php ActiveForm::end(); ?>

    <?php
        if (!empty($_GET)){
         
        $user= EventsAtendees::find()->where(['active'=>1])->andWhere(['events_id'=>$eventid]);
        
        $dataProvider = new ActiveDataProvider([
            'query' => $user,
        ]);?>
   
    <div style="font-size: 20px; margin-left: 10px; margin-bottom:30px; text-transform: uppercase">
        <label>List of Attendees for <?= Html::getAttributeValue($model, 'name') ?></label>
    </div>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,

            'columns' => [
                // Data Columns
               
            [
                'label'=> 'First Name',
                'attribute' => 'user_id',
                'value' => 'user.first_name'
            ],
            [
                'label'=> 'Last Name',
                'attribute' => 'user_id',
                'value' => 'user.last_name'
            ],
                
                //['class' => 'yii\grid\ActionColumn'],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'headerOptions' => ['style' => 'color:#337ab7'],
                'template' => '{delete}',
                'buttons' => [

                  'delete' => function ($url, $model) {
                      return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                  'title' => Yii::t('app', 'lead-delete'),
                                  'data' => [
                'confirm' => 'Are you sure you want to delete this attendee?',
                'method' => 'post',
            ],
                      ]);
                  }

                ],
                'urlCreator' => function ($action, $model, $key, $index) {

                  if ($action === 'delete') {
                      $url =\yii\helpers\Url::to(['/event/inactiveuser', 'id' => $model->user_id,'eventid'=>$model->events_id]);
                      return $url;
                  }

                }
            ],
            ],
        ]); 
?>
    
    <?php    
        } ?>
   
</div>

views/event/form_1.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use app\api\modules\v1\models\Venue;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-form">

    <?php $form = ActiveForm::begin(); ?>

  

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    
    <?= $form->field($model, 'start_date')->widget(
    DatePicker::className(), [
        // inline too, not bad
         'inline' => false, 
         // modify template for custom rendering
        //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-m-dd'
        ]
]);?>

    <?= $form->field($model, 'end_date')->widget(
    DatePicker::className(), [
        // inline too, not bad
         'inline' => false, 
         // modify template for custom rendering
        //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-m-dd'
        ]
]);?>

        <?= $form->field($model,'venue_id')->dropDownList(
 ArrayHelper::map(Venue::find()->all(), 'id', 'name'),
            ['prompt'=>'Select Venue']
            ) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Events';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        <p>
            <?= Html::a('Create Events', ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    </div>
    <div class="box-body">


        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
              
//            'id',
                [
                    'attribute' => 'image_cover',
                    'format' => 'html',
                    'value' => function ($data) {
                        return Html::img(Yii::$app->params['server'] . $data['image_cover'], ['width' => '200px', 'height'=>'90px']);
                    },
                        ],
                'name',
                'description',
                //'image_cover',
                
                        'start_date',
                        'end_date',
                        [
                            'attribute' => 'venue_id',
                            'value' => 'venue.name'
                        ],
                        //  'active',
                        // 'lastmodified',
                        // 'venue_id',
                        ['class' => 'yii\grid\ActionColumn'],
                    ],
                ]);
                ?>
    </div>
</div>

views/event/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */

$this->title = 'Update Events: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id, 'venue_id' => $model->venue_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="events-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        
    ]) ?>

</div>

views/event/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\api\modules\v1\models\Events */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id, 'venue_id' => $model->venue_id], ['class' => 'btn btn-primary']) ?>
        <?=
        Html::a('Delete', ['delete', 'id' => $model->id, 'venue_id' => $model->venue_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ])
        ?>
    </p>
  
    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [

            'name',
            'description',
            'start_date',
            'end_date',
           // 'active',
            //'lastmodified',
            [
                'attribute' => 'image_cover',
                'value' => Yii::$app->params['server'].$model->image_cover,
                'format' => ['image', ['width' => '100', 'height' => '100']],
            ],
             [
                'attribute' => 'sponsorList',
                'value' => '<div class="well">' . $model->sponsors . '</div',
                'format' => ['html'],
            ],
           
//                 'sponsorList' => $model->sponsors,
                
             //   'format' => ['image', ['width' => '100', 'height' => '100']],
            
            
        ],
    ])
    ?>

</div>